server:
  port: 8003

spring:
  cloud:
    application:
      name: cloud-gateway-service
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: payment_routh #路由ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
#          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          uri: lb://nacos-payment #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/** #断言，路径相匹配的进行路由
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true   #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了），比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上。


#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.djy.springcloud.entity  #所有Entity别名类所在包


#Eureka
#eureka:
#  client:
#    #默认自己注册进eurekaServer
#    register-with-eureka: true
#    #是否从EurekaServer抓取已有注册信息，集群必须设置为true才能配合ribbon使用负载均很
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:7001/eureka/
#  instance:
#   instance-id: gateway8003



