server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: scott
    password: root
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.djy.springcloud.entity


#Eureka
eureka:
  client:
    #默认自己注册进eurekaServer
    register-with-eureka: true
    #是否从EurekaServer抓取已有注册信息，集群必须设置为true才能配合ribbon使用负载均很
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:7001/eureka/
  instance:
   instance-id: payment8001