server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: nacos-payment
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: scott
    password: root
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.djy.springcloud.entity

